spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.dundunmonster.springboottransactional.entity